-- 4. Crear la llave primaria en el tablespace de índices
ALTER TABLE GE.People ADD CONSTRAINT pk_people PRIMARY KEY (id_people) 
USING INDEX 
TABLESPACE GE_Index PCTFREE 20
STORAGE (
    INITIAL 10K
    NEXT 10K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
);

ALTER TABLE GE.Phone ADD CONSTRAINT pk_phone PRIMARY KEY (id_phone) 
USING INDEX 
TABLESPACE GE_Index PCTFREE 20
STORAGE (
    INITIAL 10K
    NEXT 10K
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
);

ALTER TABLE GE.PhonexPeople ADD CONSTRAINT pk_phonexpeople PRIMARY KEY (phone_id, person_id);