-- 6. Crear el esquema AD
CREATE USER AD 
    IDENTIFIED BY ad
    DEFAULT TABLESPACE GE_Data
    QUOTA 10M ON GE_Data
    TEMPORARY TABLESPACE temp
    QUOTA 5M ON SYSTEM;

GRANT CONNECT to AD;
GRANT CREATE SESSION to AD;
GRANT CREATE TABLE to AD;