CREATE TABLESPACE GE_Data
    DATAFILE 'C:\app\dilan\oradata\DBProyecto\gedata01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512k
    MAXSIZE 200M;

CREATE TABLESPACE GE_Index
    DATAFILE 'C:\app\dilan\oradata\DBProyecto\geindex01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512k
    MAXSIZE 200M;
    
GRANT CONNECT to GE;
GRANT CREATE TABLE to GE;
GRANT CREATE SEQUENCE TO GE;
GRANT CONNECT to GE;
GRANT CREATE SESSION to GE;
GRANT CREATE PROCEDURE TO GE;
GRANT CREATE TRIGGER TO GE;
GRANT CREATE JOB TO GE;