CREATE TABLE EMPLOYEE(
    ID NUMBER NOT NULL, CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID),
    FIRST_NAME      VARCHAR2(50), 
    SECOND_NAME     VARCHAR2(50), 
    FIRST_SURNAME   VARCHAR2(50), 
    SECOND_SURNAME  VARCHAR2(50),  
    SALARY NUMBER,
    BIRTHDAY DATE
)
TABLESPACE GE_Data
STORAGE (
    INITIAL 6144 NEXT 6144 MINEXTENTS 1 MAXEXTENTS 5
);

CREATE SEQUENCE GE.employee_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE;