CREATE TABLESPACE GE_Data
    DATAFILE 'C:\app\dilan\oradata\DBProyecto\gedata01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512k
    MAXSIZE 200M;

CREATE TABLESPACE GE_Index
    DATAFILE 'C:\app\dilan\oradata\DBProyecto\geindex01.dbf'
    SIZE 10M
    REUSE
    AUTOEXTEND ON
    NEXT 512k
    MAXSIZE 200M;

-- Crear el esquema GE
CREATE USER GE 
    IDENTIFIED BY ge
    DEFAULT TABLESPACE GE_Data
    QUOTA 10M ON GE_Data
    TEMPORARY TABLESPACE temp
    QUOTA 5M ON SYSTEM
    QUOTA 10M ON GE_Index;

GRANT CONNECT to GE;
GRANT CREATE TABLE to GE;

CREATE TABLE GE.EMPLOYEE(
    ID NUMBER NOT NULL, CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID),
    FIRST_NAME      VARCHAR2(50), 
    SECOND_NAME     VARCHAR2(50), 
    FIRST_SURNAME   VARCHAR2(50), 
    SECOND_SURNAME  VARCHAR2(50),  
    SALARY NUMBER,
    BIRTHDAY DATE
)
TABLESPACE GE_Data
STORAGE (
    INITIAL 6144 NEXT 6144 MINEXTENTS 1 MAXEXTENTS 5
);

CREATE TABLE GE.DEPARTMENT(
    ID NUMBER NOT NULL, CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID),
    NAME VARCHAR2(50),
    MANAGER_ID NUMBER,
    CONSTRAINT FK_DEPARTMENT_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES GE.EMPLOYEE(ID)
)
TABLESPACE GE_Data
STORAGE (
    INITIAL 6144 NEXT 6144 MINEXTENTS 1 MAXEXTENTS 5
);